import Head from "next/head";
import Layout from "../layout/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Seong&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </>
  );
}
